### ISSUE TITLE
Header Bar

### ISSUE THREAD

**Issue by asilenced** [asilenced/Boston_Next.js#1]
In AppHeader component, I want to place the search bar at the centre of the header bar.
How to do this? Please help me.

**Comment by 486xtm** [comment]
> In AppHeader component, I want to place the search bar at the centre of the header bar. How to do this? Please help me.

This is a sample CSS problem.
if you want to place the search bar at the center , you have to add CSS in Search bar div.
Here is a sample CSS
.searchBar {
  alignItems: center;
  justifyContent; center;
 .....
}

**Comment by asilenced** [comment]
Thanks for your concern. 

> > In AppHeader component, I want to place the search bar at the centre of the header bar. How to do this? Please help me.
> 
> This is a sample CSS problem. if you want to place the search bar at the center , you have to add CSS in Search bar div. Here is a sample CSS .searchBar { alignItems: center; justifyContent; center; ..... }

Thanks for your concern. But where can I implement this CSS style? Which component and which div element?

**Comment by 486xtm** [comment]
> Thanks for your concern.
> 
> > > In AppHeader component, I want to place the search bar at the centre of the header bar. How to do this? Please help me.
> > 
> > 
> > This is a sample CSS problem. if you want to place the search bar at the center , you have to add CSS in Search bar div. Here is a sample CSS .searchBar { alignItems: center; justifyContent; center; ..... }
> 
> Thanks for your concern. But where can I implement this CSS style? Which component and which div element?

you have to import CSS file in a root component and implement like this. Here is a example 
<div className = "searchBar" ... > <SearchBar/> <div>

**Comment by 486xtm** [comment]
> > Thanks for your concern.
> > > > In AppHeader component, I want to place the search bar at the centre of the header bar. How to do this? Please help me.
> > > 
> > > 
> > > This is a sample CSS problem. if you want to place the search bar at the center , you have to add CSS in Search bar div. Here is a sample CSS .searchBar { alignItems: center; justifyContent; center; ..... }
> > 
> > 
> > Thanks for your concern. But where can I implement this CSS style? Which component and which div element?
> 
> you have to import CSS file in a root component and implement like this. Here is a example
<div className = "Searchbar" ...> <SearchBar/> </div>

**Comment by 486xtm** [comment]
> > > Thanks for your concern.
> > > > > In AppHeader component, I want to place the search bar at the centre of the header bar. How to do this? Please help me.
> > > > 
> > > > 
> > > > This is a sample CSS problem. if you want to place the search bar at the center , you have to add CSS in Search bar div. Here is a sample CSS .searchBar { alignItems: center; justifyContent; center; ..... }
> > > 
> > > 
> > > Thanks for your concern. But where can I implement this CSS style? Which component and which div element?
> > 
> > 
> > you have to import CSS file in a root component and implement like this. Here is a example <div> <SearchBar/> </div>

**Comment by asilenced** [comment]
> > > > Thanks for your concern.
> > > > > > In AppHeader component, I want to place the search bar at the centre of the header bar. How to do this? Please help me.
> > > > > 
> > > > > 
> > > > > This is a sample CSS problem. if you want to place the search bar at the center , you have to add CSS in Search bar div. Here is a sample CSS .searchBar { alignItems: center; justifyContent; center; ..... }
> > > > 
> > > > 
> > > > Thanks for your concern. But where can I implement this CSS style? Which component and which div element?
> > > 
> > > 
> > > you have to import CSS file in a root component and implement like this. Here is a example

Thank you very much, @486xtm. I got it and I have solved the problem.
